### ISSUE TITLE
Files type authorized in the repo

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/.github#6]
@akouete-kpakpo stated
>I take this opportunity to start a topic about the types of files accepted in the repo. In my opinion we should only accept code files not binaries. That means no pdf, ppt etc. I would even add no images.
The reason is that it's impossible to see the diff on the binary files. So you end up with obsolete files. For example the pdf's that come from the conversion of a notebook, are no longer consistent with the notebooks as soon as they are modified.
I think that the PDFs must be elsewhere, for example on Dropbox.
In short, let's do it as cleanly as the big repos for example `numpy` or `sklearn`.

In ML-for-B-E/.github#5 we should take into account the comment above.

**Comment by BWhannou** [comment]
resolved with #5
